stages:
  build-dataset:
    cmd: bin/build-dataset
    deps:
      - artifacts/data/raw
      - bin/build-dataset
    outs:
      - artifacts/data/processed
    params:
      - data
  build-features:
    cmd: bin/build-features
    deps:
      - artifacts/data/processed
      - bin/build-features
    outs:
      - artifacts/features
    