stages:
  build-dataset:
    cmd: bin/build-dataset
    deps:
      - artefacts/data/raw
      - bin/build-dataset
    outs:
      - artefacts/data/processed
    params:
      - data
  build-features:
    cmd: bin/build-features
    deps:
      - artefacts/data/processed
      - bin/build-features
    outs:
      - artefacts/features
  train-model:
    cmd: bin/train-model
    deps:
      - artefacts/data/processed
      - artefacts/features
    params:
      - model
metrics:
  - experiments/metrics.json
plots:
  - experiments/plots/metrics:
      x: step