random_seed: 42
data:
  test_size: 0.2
features:
  numerical:
    - age
    - hip
    - abdomen
    - BAI
    - WHR
    - BMI
  categorical:
    - sex
model:
  n_estimators: 10
  max_depth: 2
  learning_rate: 0.05

